version: '3'
services:

  mongodb:
      image: mongo:latest
      ports:
        - 27017:27017
      command: --smallfiles

  node:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/devtest
    ports:
      - 3000:3000
    links:
      - mongodb
    command: npm start

